### ISSUE TITLE
Create a 1.0.0 release, and get releases and snapshots published via CI.

### ISSUE THREAD

**Issue by mzamani1** [dropwizard/dropwizard-kafka#1]
Hoping for some help from @joschi or any other @dropwizard-committers who's familiar with what the process is to get artifact publishing all set up!

**Comment by mzamani1** [comment]
I did create this: https://issues.sonatype.org/browse/OSSRH-48580

But I'm not sure who has a `deployer` role for `io.dropwizard.modules`

**Comment by joschi** [comment]
@mzamani1 We have a dedicated account at Sonatype OSS for publishing artifacts, no need to get individual access there. I'll take a look at setting up the release process on the weekend.

**Comment by mzamani1** [comment]
@joschi That'd be great, thanks! I'll try to get a few more modules up this week, so we can knock a few out this weekend.

**Comment by joschi** [comment]
This should work as soon as https://issues.sonatype.org/browse/OSSRH-48760 has been resolved.

**Comment by mzamani1** [comment]
Planning on getting a `1.0.0` release published later this week/weekend.

**Comment by mzamani1** [comment]
Published `1.3.11-1`
