### ISSUE TITLE
Add ClusterHealthCheck using AdminClient

### ISSUE THREAD

**Issue by cricket007** [dropwizard/dropwizard-kafka#10]
With #9 it would be easy to add a cluster description healthcheck. 

https://github.com/jeqo/dropwizard-modules/blob/master/kafka/src/main/java/io/github/jeqo/dropwizard/kafka/KafkaClientHealthCheck.java

**Comment by saurav-2104** [comment]
Also, would like to understand if there is a way to replace healthchecks done by https://github.com/dropwizard/dropwizard-kafka/blob/master/src/main/java/io/dropwizard/kafka/CheckableConsumer.java

**Comment by mzamani1** [comment]
@cricket007 See #15

**Comment by mzamani1** [comment]
@saurav-2104 Provided a way to override the default health check in #14. Also, in #15 I'm removing the `CheckableConsumer`, as it really doesn't provide much value that the AdminClient can't handle better.

**Comment by mzamani1** [comment]
Fixed in release `1.3.12-2`
