### ISSUE TITLE
Is this ready for GA?

### ISSUE THREAD

**Issue by OOPMan** [dropwizard/dropwizard-kafka#22]
I'm asking because I tried adding it to my project and the basic usage example in the README.md doesn't seem to work...

Also, what's with KafkaProducerBundler expecting the the dropwizard configuration type to inherit from `javax.security.auth.login.Configuration` rather than `io.dropwizard.Configuration`? Is this a bug?

**Comment by mzamani1** [comment]
@OOPMan can you clarify what doesn’t work from the example?

> Also, what's with KafkaProducerBundler expecting the the dropwizard configuration type to inherit from javax.security.auth.login.Configuration rather than io.dropwizard.Configuration? Is this a bug?

That would be a bug, yes.

**Comment by mzamani1** [comment]
@OOPMan Also, I get the frustration. This library is a modified version of one we use internally at Apple, as we have a modified Kafka Client we use internally. When open sourcing this, I added the `Bundle`s, as previously I would recommend users interact with the `Factory`s directly. So that's one area that I need to test better, and have an example project that illustrates (and verifies) usage.

**Comment by mzamani1** [comment]
`1.3.12-3` released fixing the incorrect `Configuration` class issue 
https://github.com/dropwizard/dropwizard-kafka/releases/tag/dropwizard-kafka-1.3.12-3

**Comment by OOPMan** [comment]
@mzamani1 Thanks for that quick fix. My issue around the example was that it shows:
```java
private final KafkaProducerBundle<ExampleConfiguration> kafkaProducer = new KafkaProducerBundle<ExampleConfiguration>() {
    @Override
    public KafkaProducerFactory getKafkaProducerFactory(ExampleConfiguration configuration) {
        return configuration.getKafkaProducerFactory();
    }
};
```

but `KafkaProducerBundle` is defined with three type parameters and thus IntelliJ claims it won't compile (maybe it's wrong?)

Also, I think `getKafkaProducerFactory` also has three type parameters...

I'm working on JDK8, fyi...

**Comment by mzamani1** [comment]
@OOPMan yeah, that’s a doc issue, and is my bad. The three type parameters are: 

1. The Key type for your producer
2. The Value type for your producer
3. The configuration type

**Comment by mzamani1** [comment]
I’ll fix the doc issue once I get to my office.

**Comment by mzamani1** [comment]
@OOPMan docs should be fixed now. Thanks for bearing with me.

**Comment by OOPMan** [comment]
@mzamani1 Thanks for the timely response, will try again :-)

**Comment by OOPMan** [comment]
@mzamani1 Much better, although the example still has a minor issue due to `KafkaProducerBundle` not having a default constructor, but that's not a train smash since it's easy to work out what to do :-)

**Comment by mzamani1** [comment]
@OOPMan Gotcha, I’ll look at that as well. Thanks for all of the feedback!
