### ISSUE TITLE
Add dropwizard-kafka to Dropwizard modules directory

### ISSUE THREAD

**Issue by joschi** [dropwizard/dropwizard-kafka#42]
Please consider adding this project to the list of official Dropwizard modules at https://modules.dropwizard.io/.

https://github.com/dropwizard/modules.dropwizard.io/blob/8724c877edb55517a62f1662b9063e373a8d821a/_data/modules/official.yaml

**Comment by cricket007** [comment]
Seems to be there already

https://github.com/dropwizard/modules.dropwizard.io/blob/gh-pages/_data/modules/official.yaml#L56

**Comment by mzamani1** [comment]
Yep, already added it. Closing this.
