### ISSUE TITLE
Add SASL plaintext security configuration

### ISSUE THREAD

**Issue by saeedshahab** [dropwizard/dropwizard-kafka#61]
At the moment, dropwizard-kafka does not support SASL plaintext authentication to Kafka server.  The difference between SASL SSL and plaintext security is the absence of ```ssl.protocol```  configuration key, whose value is set to ```TLSv1.2```, during setup.

**Comment by mzamani1** [comment]
Thanks for the issue and PR! I’ll cut a release of this a little later today.

**Comment by mzamani1** [comment]
Released in version `1.4.0`

**Comment by saeedshahab** [comment]
Hi @mzamani1, version ```1.4.0``` is not found on Maven central. Please can you publish it there?
