### ISSUE TITLE
Latest Release tags not working

### ISSUE THREAD

**Issue by cricket007** [dropwizard/dropwizard-kafka#63]
Looks like there are releases after the current "latest" one marked .

https://github.com/dropwizard/dropwizard-kafka/releases

**Comment by mzamani1** [comment]
Updated to make the release that was just cut the latest, `1.4.0`.

**Comment by saeedshahab** [comment]
Hi @mzamani1, we are unable to find version ```1.4.0``` on Maven central. Please can you publish it there?
